<a href="https://colab.research.google.com/github/pawarmanthan460-sys/PDS--Assigenment/blob/main/Practicalno_4ManthanPawarRollno65batchB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name : Manthan Dharmaraj Pawar

Class : Second Year

Div : SY-B

Roll no.: 65

                            Practical no.: 4

Aim: To perform numerical computations efficiently using the Numpy library in python.

Theory:

### Q1. Explain the Role of NumPy in the Python Scientific Computing Ecosystem
NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. Its primary role is to serve as the foundational data structure (`ndarray`) and the core computational engine for the entire Python scientific computing ecosystem. Most other scientific libraries, such as SciPy, Pandas, Matplotlib, and Scikit-learn, are built on top of or integrate seamlessly with NumPy arrays. This allows for efficient data manipulation, numerical algorithms, and data analysis tasks.

### Q2. Why is NumPy considered faster than pure Python computations?
NumPy's performance superiority over pure Python comes from several key factors:

1.  **Vectorization:** NumPy operations are typically performed on entire arrays rather than individual elements. This process, known as vectorization, allows NumPy to apply functions to all elements in an array at once, rather than using explicit Python loops. Python loops are inherently slow due to their interpretive nature.
2.  **C Implementation:** The core of NumPy, including its `ndarray` object and many of its functions, is implemented in C and Fortran. This means that when you perform an operation in NumPy, you're essentially calling highly optimized, compiled C code, which is significantly faster than interpreted Python code.
3.  **Contiguous Memory Allocation:** NumPy arrays store data in contiguous blocks of memory. This allows for efficient caching and significantly faster access to elements by the CPU, as opposed to Python's built-in lists, which can store elements at dispersed memory locations.
4.  **Optimized Algorithms:** The mathematical operations provided by NumPy are implemented using highly optimized linear algebra libraries (like BLAS and LAPACK), which are specifically designed for high-performance numerical computations.

### Q3. What types of mathematical operations can be performed using NumPy?
NumPy supports a vast array of mathematical operations, categorizing them broadly as:

1.  **Element-wise Operations:** Basic arithmetic operations (+, -, *, /, %), exponentiation (`**`), and trigonometric functions (`sin`, `cos`, `tan`), logarithmic functions (`log`, `log10`), and many more can be applied element-wise to arrays.
2.  **Aggregate Functions:** Functions that compute statistics over an entire array or along specific axes, such as `sum()`, `mean()`, `median()`, `min()`, `max()`, `std()` (standard deviation), `var()` (variance), `prod()` (product), etc.
3.  **Linear Algebra:** NumPy is a powerful tool for linear algebra, offering functions for matrix multiplication (`@` operator or `np.dot()`), dot products, cross products, determinants (`np.linalg.det()`), inverse matrices (`np.linalg.inv()`), eigenvalues and eigenvectors (`np.linalg.eig()`), solving linear equations (`np.linalg.solve()`), and more.
4.  **Fourier Transforms:** Functions for computing discrete Fourier transforms (`np.fft.fft()`, `np.fft.ifft()`) which are crucial in signal processing.
5.  **Random Number Generation:** A robust module (`np.random`) for generating random numbers from various probability distributions (uniform, normal, binomial, etc.).
6.  **Statistical Functions:** Beyond basic aggregates, it includes functions for correlation (`np.corrcoef()`), covariance (`np.cov()`), histograms (`np.histogram()`), etc.

### Q4. Explain Indexing and Slicing in NumPy Arrays
Indexing and slicing in NumPy arrays are similar to Python lists but offer more advanced capabilities, especially for multi-dimensional arrays.

*   **Indexing:** This refers to accessing individual elements or subsets of elements using their position. For a 1D array, it's `arr[index]`. For a 2D array, it's `arr[row_index, col_index]`. NumPy also supports Boolean indexing (selecting elements based on a condition, e.g., `arr[arr > 5]`) and fancy indexing (selecting elements using an array of indices, e.g., `arr[[0, 2, 4]]`).

*   **Slicing:** This refers to extracting sub-arrays or views of an array using a range of indices. The syntax is `start:stop:step`. Like Python lists, the `stop` index is exclusive. For a 1D array, `arr[start:stop]` creates a slice. For multi-dimensional arrays, you can slice along each dimension, for example, `arr[row_start:row_stop, col_start:col_stop]`. A key aspect of NumPy slicing is that it creates a *view* into the original array, not a copy. This means modifying a slice will also modify the original array, which is memory-efficient.

### Q5. How does NumPy integrate with libraries like Pandas, Matplotlib, and Scikit-learn?
NumPy's `ndarray` is the lingua franca of the Python scientific stack, ensuring seamless integration with other major libraries:

*   **Pandas:** Pandas DataFrames and Series are built on top of NumPy arrays. When you create a DataFrame, its columns are essentially NumPy arrays. This allows Pandas to leverage NumPy's high-performance numerical operations for data manipulation, cleaning, and analysis. Data can be easily converted between Pandas objects and NumPy arrays using `.values` or `to_numpy()` methods.

*   **Matplotlib:** Matplotlib, the primary plotting library in Python, uses NumPy arrays as its preferred input format for plotting data. Whether you're plotting lines, scatter plots, histograms, or images, the data is typically provided as NumPy arrays. This allows Matplotlib to efficiently render complex visualizations directly from the numerical data structures provided by NumPy.

*   **Scikit-learn:** Scikit-learn, the leading machine learning library in Python, expects its input data (features and targets) to be in the form of NumPy arrays. All algorithms within Scikit-learn operate directly on `ndarray` objects. This standardization allows for efficient data processing, model training, and prediction, leveraging NumPy's optimized computations. When working with Pandas DataFrames, they are typically converted to NumPy arrays before being fed into Scikit-learn models.

In [ ]:
Code:

## Weak Students (Basic)

### 1. Create a NumPy array from a list.

In [ ]:
# Create a Python list
python_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
numpy_array_from_list = np.array(python_list)

print("NumPy Array from List:", numpy_array_from_list)
print("Type of the array:", type(numpy_array_from_list))

NumPy Array from List: [1 2 3 4 5]
Type of the array: <class 'numpy.ndarray'>


### 2. Perform basic arithmetic operations on arrays.

In [ ]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

# Addition
print("Addition:", array1 + array2)

# Subtraction
print("Subtraction:", array1 - array2)

# Multiplication (element-wise)
print("Multiplication:", array1 * array2)

# Division (element-wise)
print("Division:", array1 / array2)

# Exponentiation
print("Exponentiation (array1 ** 2):", array1 ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Exponentiation (array1 ** 2): [ 100  400  900 1600]


### 3. Find sum and mean of array elements.

In [ ]:
data_array = np.array([10, 15, 20, 25, 30])

# Sum of all elements
print("Sum of elements:", data_array.sum())

# Mean of all elements
print("Mean of elements:", data_array.mean())

Sum of elements: 100
Mean of elements: 20.0


### 4. Reshape a one-dimensional array.

In [ ]:
one_dim_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original 1D array:\n", one_dim_array)
print("Shape of original array:", one_dim_array.shape)

# Reshape to a 3x3 two-dimensional array
reshaped_array = one_dim_array.reshape(3, 3)
print("\nReshaped 3x3 array:\n", reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)

Original 1D array:
 [1 2 3 4 5 6 7 8 9]
Shape of original array: (9,)

Reshaped 3x3 array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of reshaped array: (3, 3)


### 5. Access specific elements using indexing.

In [ ]:
my_array = np.array([[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]])
print("Original array:\n", my_array)

# Access a single element (row 0, column 1)
print("\nElement at (0, 1):", my_array[0, 1])

# Access a whole row (row 1)
print("Row 1:", my_array[1])

# Access a whole column (column 2)
print("Column 2:", my_array[:, 2])

# Slicing: Access a sub-array (rows 0-1, columns 0-1)
print("Sub-array (rows 0-1, cols 0-1):\n", my_array[0:2, 0:2])

# Boolean indexing: Elements greater than 14
print("Elements > 14:", my_array[my_array > 14])

Original array:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

Element at (0, 1): 11
Row 1: [13 14 15]
Column 2: [12 15 18]
Sub-array (rows 0-1, cols 0-1):
 [[10 11]
 [13 14]]
Elements > 14: [15 16 17 18]


## Normal Students (Moderate)

### 6. Perform matrix addition and multiplication.

In [ ]:
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix Addition (element-wise)
print("\nMatrix Addition (A + B):\n", matrix_a + matrix_b)

# Matrix Multiplication (dot product)
# Use np.dot() or the @ operator
print("\nMatrix Multiplication (A @ B):\n", matrix_a @ matrix_b)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]


### 7. Generate random numbers using NumPy.

In [ ]:
# Generate a single random float between 0 and 1
print("Single random float:", np.random.rand())

# Generate an array of 5 random floats between 0 and 1
print("\nArray of 5 random floats:", np.random.rand(5))

# Generate a 2x3 array of random floats from a standard normal distribution (mean=0, std=1)
print("\n2x3 array from standard normal distribution:\n", np.random.randn(2, 3))

# Generate random integers between 1 and 100 (exclusive of 101)
print("\nRandom integer between 1 and 100:", np.random.randint(1, 101))

# Generate a 3x3 array of random integers between 0 and 9 (exclusive of 10)
print("\n3x3 array of random integers (0-9):\n", np.random.randint(0, 10, size=(3, 3)))

Single random float: 0.6848985134660203

Array of 5 random floats: [0.50884767 0.4477155  0.25359689 0.52906279 0.74038642]

2x3 array from standard normal distribution:
 [[ 0.03297617 -0.17407877 -1.05346693]
 [ 0.44879068  1.06106901  0.21603242]]

Random integer between 1 and 100: 65

3x3 array of random integers (0-9):
 [[9 4 7]
 [7 5 7]
 [1 5 1]]


### 8. Compute standard deviation and variance.

In [ ]:
stats_array = np.array([10, 12, 15, 12, 18, 20, 15, 16])
print("Data array:", stats_array)

# Standard deviation
print("Standard Deviation:", np.std(stats_array))

# Variance
print("Variance:", np.var(stats_array))

Data array: [10 12 15 12 18 20 15 16]
Standard Deviation: 3.112474899497183
Variance: 9.6875


### 9. Use NumPy functions for mathematical operations.

In [ ]:
angles = np.array([0, np.pi/2, np.pi]) # 0, 90 degrees, 180 degrees

# Sine function
print("Sine of angles:", np.sin(angles))

# Cosine function
print("Cosine of angles:", np.cos(angles))

# Exponential function (e^x)
exp_array = np.array([0, 1, 2])
print("\nExponential of array elements:", np.exp(exp_array))

# Natural logarithm (ln(x))
log_array = np.array([1, np.exp(1), np.exp(2)]) # 1, e, e^2
print("\nNatural log of array elements:", np.log(log_array))

Sine of angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of angles: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

Exponential of array elements: [1.         2.71828183 7.3890561 ]

Natural log of array elements: [0. 1. 2.]


### 10. Compare Python lists and NumPy arrays (speed and memory).

In [ ]:
import time
import sys

list_size = 1000000

# Python List
python_list = list(range(list_size))

# NumPy Array
numpy_array = np.arange(list_size)

print(f"Comparing data structures with {list_size} elements:")

# Memory Usage
print("\n--- Memory Usage ---")
print(f"Size of Python List: {sys.getsizeof(python_list)} bytes")
print(f"Size of NumPy Array: {numpy_array.nbytes} bytes (approx, actual may vary)")

# Speed Comparison: Addition
print("\n--- Speed Comparison (Addition) ---")

start_time = time.time()
python_list_sum = sum(python_list)
end_time = time.time()
print(f"Python List sum time: {end_time - start_time:.6f} seconds")

start_time = time.time()
numpy_array_sum = np.sum(numpy_array)
end_time = time.time()
print(f"NumPy Array sum time: {end_time - start_time:.6f} seconds")

# Speed Comparison: Element-wise Multiplication
print("\n--- Speed Comparison (Element-wise Multiplication) ---")

# For Python lists, element-wise multiplication requires a loop or list comprehension
start_time = time.time()
result_list = [x * 2 for x in python_list]
end_time = time.time()
print(f"Python List element-wise multiplication time: {end_time - start_time:.6f} seconds")

start_time = time.time()
result_numpy = numpy_array * 2
end_time = time.time()
print(f"NumPy Array element-wise multiplication time: {end_time - start_time:.6f} seconds")

print("\nConclusion: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations than Python lists, especially with large datasets, due to vectorization and C implementation.")

Comparing data structures with 1000000 elements:

--- Memory Usage ---
Size of Python List: 8000056 bytes
Size of NumPy Array: 8000000 bytes (approx, actual may vary)

--- Speed Comparison (Addition) ---
Python List sum time: 0.011570 seconds
NumPy Array sum time: 0.000955 seconds

--- Speed Comparison (Element-wise Multiplication) ---
Python List element-wise multiplication time: 0.058191 seconds
NumPy Array element-wise multiplication time: 0.005202 seconds

Conclusion: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations than Python lists, especially with large datasets, due to vectorization and C implementation.


## Bright Students (Advanced)

### 11. Implement vectorized operations for performance comparison.

In [ ]:
import time

def pure_python_sum_of_squares(n):
    result = 0
    for i in range(n):
        result += i**2
    return result

def numpy_sum_of_squares(n):
    arr = np.arange(n)
    return np.sum(arr**2)

n = 10000000 # Ten million elements

print(f"Comparing sum of squares for {n} elements:")

# Pure Python version
start_time = time.time()
python_result = pure_python_sum_of_squares(n)
end_time = time.time()
python_time = end_time - start_time
print(f"Pure Python time: {python_time:.6f} seconds")

# NumPy vectorized version
start_time = time.time()
numpy_result = numpy_sum_of_squares(n)
end_time = time.time()
numpy_time = end_time - start_time
print(f"NumPy vectorized time: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f} times faster for this operation.")

Comparing sum of squares for 10000000 elements:
Pure Python time: 1.004190 seconds
NumPy vectorized time: 0.079953 seconds

NumPy is approximately 12.56 times faster for this operation.


### 12. Solve a system of linear equations.

In [ ]:
# Consider the system of equations:
# 2x + 3y = 11
# x  -  y =  3

# Represent the coefficients in a NumPy array (matrix A)
A = np.array([[2, 3],
              [1, -1]])

# Represent the constants in a NumPy array (vector B)
B = np.array([11, 3])

print("Coefficient Matrix A:\n", A)
print("Constant Vector B:\n", B)

# Solve the system using np.linalg.solve()
X = np.linalg.solve(A, B)

print("\nSolution (x, y):", X)
print(f"Verification: 2*{X[0]:.2f} + 3*{X[1]:.2f} = {2*X[0] + 3*X[1]:.2f} (should be ~11)")
print(f"Verification: {X[0]:.2f} - {X[1]:.2f} = {X[0] - X[1]:.2f} (should be ~3)")

Coefficient Matrix A:
 [[ 2  3]
 [ 1 -1]]
Constant Vector B:
 [11  3]

Solution (x, y): [4. 1.]
Verification: 2*4.00 + 3*1.00 = 11.00 (should be ~11)
Verification: 4.00 - 1.00 = 3.00 (should be ~3)


### 13. Perform broadcasting operations.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("Vector:\n", vector)

# Broadcasting: Add the vector to each row of the matrix
# NumPy automatically 'stretches' the vector to match the dimensions of the matrix rows
print("\nMatrix + Vector (broadcasting):\n", matrix + vector)

# Another example: Multiply a 2D array by a 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 100, 1000])
print("\n2D Array:\n", arr2d)
print("1D Array:\n", arr1d)
print("\n2D Array * 1D Array (broadcasting):\n", arr2d * arr1d)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [10 20 30]

Matrix + Vector (broadcasting):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [  10  100 1000]

2D Array * 1D Array (broadcasting):
 [[  10  200 3000]
 [  40  500 6000]]


### 14. Analyze large datasets using NumPy arrays.

In [ ]:
# Create a large random dataset (e.g., 1 million data points, 3 features)
large_data = np.random.rand(1000000, 3)
print(f"Shape of large dataset: {large_data.shape}")

# Calculate mean of each feature (column)
mean_per_feature = np.mean(large_data, axis=0)
print("\nMean of each feature:", mean_per_feature)

# Calculate standard deviation of each feature
std_per_feature = np.std(large_data, axis=0)
print("Standard Deviation of each feature:", std_per_feature)

# Find the maximum value in the entire dataset
max_value = np.max(large_data)
print("\nMaximum value in dataset:", max_value)

# Find the minimum value in each row
min_per_row = np.min(large_data, axis=1)
print("Minimum value in first 5 rows:", min_per_row[:5])

# Count elements satisfying a condition (e.g., > 0.9)
count_gt_0_9 = np.sum(large_data > 0.9)
print("\nNumber of elements greater than 0.9:", count_gt_0_9)

# Normalize the dataset (Min-Max scaling for example)
min_vals = np.min(large_data, axis=0)
max_vals = np.max(large_data, axis=0)
normalized_data = (large_data - min_vals) / (max_vals - min_vals)
print("\nNormalized data (first 5 rows):\n", normalized_data[:5])

Shape of large dataset: (1000000, 3)

Mean of each feature: [0.50033916 0.49983825 0.49989228]
Standard Deviation of each feature: [0.28857626 0.28850814 0.28868498]

Maximum value in dataset: 0.9999999878859871
Minimum value in first 5 rows: [0.0182133  0.20068617 0.32840809 0.10902887 0.3207802 ]

Number of elements greater than 0.9: 299718

Normalized data (first 5 rows):
 [[0.3804544  0.01821214 0.63981451]
 [0.20068623 0.79763675 0.57851493]
 [0.32840849 0.6694012  0.60185609]
 [0.1090287  0.27563546 0.48298988]
 [0.42702095 0.3207794  0.69532075]]


### 15. Optimize numerical computations using NumPy functions.

In [ ]:
import time

# Task: Calculate the pairwise Euclidean distance between all points in two sets of 2D points.

points1 = np.random.rand(1000, 2) # 1000 points, 2 dimensions
points2 = np.random.rand(1000, 2) # 1000 points, 2 dimensions

# Pure Python (nested loops - highly inefficient for large data)
def euclidean_distance_python(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

start_time = time.time()
distances_python = []
# This loop will be very slow for 1000x1000 comparisons
# For demonstration, we'll only do a few to avoid extreme runtime
# for i in range(min(100, points1.shape[0])):
#     for j in range(min(100, points2.shape[0])):
#         distances_python.append(euclidean_distance_python(points1[i], points2[j]))
# end_time = time.time()
# print(f"Pure Python pairwise distance (partial): {end_time - start_time:.6f} seconds")
print("Pure Python pairwise distance computation is too slow for large N, skipping full run.")

# NumPy Vectorized (optimized)
start_time = time.time()
# Expand dimensions to allow broadcasting: (N, 1, D) - (1, M, D) -> (N, M, D)
diff = points1[:, np.newaxis, :] - points2[np.newaxis, :, :]
sq_diff = diff**2
sum_sq_diff = np.sum(sq_diff, axis=2)
distances_numpy = np.sqrt(sum_sq_diff)
end_time = time.time()
print(f"\nNumPy Vectorized pairwise distance (full): {end_time - start_time:.6f} seconds")

print("\nShape of NumPy distance matrix (1000x1000):", distances_numpy.shape)
print("First 5x5 distances from NumPy matrix:\n", distances_numpy[:5, :5])

print("\nThis demonstrates how NumPy's vectorized operations can significantly optimize computations that would be very slow using pure Python loops, especially for operations involving multiple arrays or large datasets.")

Pure Python pairwise distance computation is too slow for large N, skipping full run.

NumPy Vectorized pairwise distance (full): 0.078465 seconds

Shape of NumPy distance matrix (1000x1000): (1000, 1000)
First 5x5 distances from NumPy matrix:
 [[0.60811533 0.41371296 0.19126196 0.2422762  0.39364101]
 [0.50147461 0.37967658 0.62455954 0.34575055 0.5354769 ]
 [0.66128846 0.4555464  0.10794364 0.23632255 0.46708053]
 [0.81298181 0.66161828 0.65226923 0.52081696 0.80289998]
 [1.07768295 0.88025206 0.54343472 0.64986483 0.97480962]]

This demonstrates how NumPy's vectorized operations can significantly optimize computations that would be very slow using pure Python loops, especially for operations involving multiple arrays or large datasets.


Conclusion:

This practical session effectively demonstrated the power and versatility of the NumPy library in Python for numerical computations. We explored its fundamental role in the scientific computing ecosystem, understanding why it's significantly faster and more memory-efficient than pure Python lists due to vectorization, C implementation, and contiguous memory allocation.

Through various tasks, we covered:
- **Basic Operations:** Creating arrays, performing element-wise arithmetic, calculating aggregates like sum and mean, reshaping arrays, and accessing elements using indexing and slicing.
- **Moderate Operations:** Implementing matrix addition and multiplication, generating various types of random numbers, and computing statistical measures like standard deviation and variance. We also used NumPy's universal functions for mathematical operations such as sine, cosine, exponential, and logarithm.
- **Advanced Applications:** Comparing vectorized operations against pure Python for performance (highlighting NumPy's speed advantage), solving systems of linear equations, understanding and utilizing broadcasting, analyzing large datasets efficiently, and optimizing numerical computations through vectorized distance calculations.

Overall, this notebook showcased that NumPy's `ndarray` is a cornerstone for high-performance numerical computing, enabling efficient data manipulation and complex mathematical operations crucial for fields like data science, machine learning, and scientific research.